"""
Production builder for DreamWeb
Compiles Python app to a self-contained deployable package (HTML shell + runtime + Python server)
"""

import os
import json
import shutil
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dreamweb.core import App

# Template for the production server launcher copied into build/
_SERVER_TEMPLATE = '''"""
DreamWeb Production Server — auto-generated by `dreamweb build`
Run with: python server.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Import the user's app module
import importlib.util, pathlib

_app_file = pathlib.Path(__file__).parent / "app_entry.py"
_spec = importlib.util.spec_from_file_location("_dreamweb_app", str(_app_file))
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default="localhost")
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()
    _mod._app.run(dev=True, host=args.host, port=args.port)
'''


class Builder:
    """Build production-ready output"""

    def __init__(self, app: "App", output_dir: str = "build"):
        self.app = app
        self.output_dir = Path(output_dir)

    def build(self):
        """Build the application for production"""
        print("🔨 Building DreamWeb app...")

        if self.output_dir.exists():
            shutil.rmtree(self.output_dir)
        self.output_dir.mkdir(parents=True)

        # Create the thin HTML shell
        self.create_html()

        # Copy the runtime JS (no embedded tree — it connects via WebSocket)
        self.create_js()

        # Write the production server launcher
        self.create_server_launcher()

        print(f"✅ Build complete!")
        print(f"📦 Output: {self.output_dir.absolute()}")
        print(f"   - index.html      (browser entry point)")
        print(f"   - dreamweb.js     (renderer + WebSocket client)")
        print(f"   - server.py       (production server launcher)")
        print(f"   - app_entry.py    (your app, referenced by server.py)")
        print(f"\n🚀 To run: cd {self.output_dir} && python server.py")

    def _extract_css(self, tree, css_parts=None):
        """Recursively extract Css widgets from component tree"""
        if css_parts is None:
            css_parts = []
        if isinstance(tree, dict):
            if tree.get("type") == "Css":
                css = tree.get("props", {}).get("css", "")
                if css:
                    css_parts.append(css)
            for child in tree.get("children", []):
                self._extract_css(child, css_parts)
        elif isinstance(tree, list):
            for item in tree:
                self._extract_css(item, css_parts)
        return css_parts

    def create_html(self):
        """Create the thin HTML shell — the tree is served dynamically by the WS server"""
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{self.app.description}">
    <title>{self.app.title}</title>
    {chr(10).join(self.app.head_tags)}
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif;
            -webkit-font-smoothing: antialiased;
        }}
        #app {{
            width: 100%;
            min-height: 100vh;
        }}
    </style>
</head>
<body>
    <div id="app"></div>
    <script src="dreamweb.js"></script>
</body>
</html>"""
        with open(self.output_dir / "index.html", "w") as f:
            f.write(html)

    def create_js(self):
        """Copy runtime.js into the build directory"""
        runtime_path = Path(__file__).parent.parent / "runtime" / "runtime.js"
        with open(runtime_path, "r") as f:
            runtime_code = f.read()

        # Strip the hot-reload comment marker; prod mode always uses WS
        runtime_code = runtime_code.replace("// Hot reload disabled in production", "")

        # Inject the auto-init bootstrap: connect to WS on the same host/port
        bootstrap = """
// Auto-initialize: connect to production server via WebSocket
(function() {
    const runtime = new DreamWebRuntime(document.getElementById('app'));
    const wsPort = parseInt(window.location.port) + 1;
    runtime.connectAndInit(window.location.hostname, wsPort);
})();
"""
        with open(self.output_dir / "dreamweb.js", "w") as f:
            f.write(runtime_code + bootstrap)

    def create_server_launcher(self):
        """Write the production server.py launcher into the build directory"""
        # Find the user's app source file and copy it
        import inspect

        app_source_file = inspect.getfile(type(self.app))

        # Write an app_entry.py that imports and exposes a `_app` instance
        entry_code = f"""# Auto-generated by DreamWeb builder — do not edit
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import importlib.util
_spec = importlib.util.spec_from_file_location("_user_app", r"{app_source_file}")
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)

# Find and instantiate the App subclass
from dreamweb.core import App as _BaseApp
_app_class = next(
    (v for v in vars(_mod).values() if isinstance(v, type) and issubclass(v, _BaseApp) and v is not _BaseApp),
    None
)
if _app_class is None:
    raise RuntimeError("No App subclass found in {app_source_file}")
_app = _app_class()
"""
        with open(self.output_dir / "app_entry.py", "w") as f:
            f.write(entry_code)

        with open(self.output_dir / "server.py", "w") as f:
            f.write(_SERVER_TEMPLATE)
